config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'opensky', to: 'home#opensky'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
require 'Opensky'

class HomeController < ApplicationController
  def index
  end

  def opensky
    @weather = Opensky.get_weather(params[:city], params[:state])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/states_helper.rb
module StatesHelper
  def us_states
    [
      ['Alabama', 'US-AL'],
      ['Alaska', 'US-AK'],
      ['Arizona', 'US-AZ'],
      ['Arkansas', 'US-AR'],
      ['California', 'US-CA'],
      ['Colorado', 'US-CO'],
      ['Connecticut', 'US-CT'],
      ['Delaware', 'US-DE'],
      ['District of Columbia', 'US-DC'],
      ['Florida', 'US-FL'],
      ['Georgia', 'US-GA'],
      ['Hawaii', 'US-HI'],
      ['Idaho', 'US-ID'],
      ['Illinois', 'US-IL'],
      ['Indiana', 'US-IN'],
      ['Iowa', 'US-IA'],
      ['Kansas', 'US-KS'],
      ['Kentucky', 'US-KY'],
      ['Louisiana', 'US-LA'],
      ['Maine', 'US-ME'],
      ['Maryland', 'US-MD'],
      ['Massachusetts', 'US-MA'],
      ['Michigan', 'US-MI'],
      ['Minnesota', 'US-MN'],
      ['Mississippi', 'US-MS'],
      ['Missouri', 'US-MO'],
      ['Montana', 'US-MT'],
      ['Nebraska', 'US-NE'],
      ['Nevada', 'US-NV'],
      ['New Hampshire', 'US-NH'],
      ['New Jersey', 'US-NJ'],
      ['New Mexico', 'US-NM'],
      ['New York', 'US-NY'],
      ['North Carolina', 'US-NC'],
      ['North Dakota', 'US-ND'],
      ['Ohio', 'US-OH'],
      ['Oklahoma', 'US-OK'],
      ['Oregon', 'US-OR'],
      ['Pennsylvania', 'US-PA'],
      ['Puerto Rico', 'US-PR'],
      ['Rhode Island', 'US-RI'],
      ['South Carolina', 'US-SC'],
      ['South Dakota', 'US-SD'],
      ['Tennessee', 'US-TN'],
      ['Texas', 'US-TX'],
      ['Utah', 'US-UT'],
      ['Vermont', 'US-VT'],
      ['Virginia', 'US-VA'],
      ['Washington', 'US-WA'],
      ['West Virginia', 'US-WV'],
      ['Wisconsin', 'US-WI'],
      ['Wyoming', 'US-WY']
    ]
  end
end

app/views/home/index.html.erb
<div>
  <%= form_tag opensky_path, method: "get", class: "form_inline" do %>
  <%= text_field_tag :city, nil, class: "form-control", placeholder: "City Name" %>
  <%= select_tag :state, options_for_select(us_states), :prompt => "Please select", class: "form-control" %>
  <%= submit_tag "Check Weather", name: nil, class: "btn btn-primary" %>
  <% end %>
</div>


<div>
<% if @weather.present? %>
  <h3><%= @weather.location %></h3>
  <p>The temperature is:
    <%= @weather.temp %> °F</p>
  <p>Current conditions:
    <%= @weather.desc %></p>
  <p>Feels like:
    <%= @weather.feels_like %> °F</p>
</div>

<% end %>

app/views/home/opensky.html.erb
<div>
  <%= form_tag opensky_path, method: "get", class: "form_inline" do %>
  <%= text_field_tag :city, nil, class: "form-control", placeholder: "City Name" %>
  <%= select_tag :state, options_for_select(us_states), :prompt => "Please select", class: "form-control" %>
  <%= submit_tag "Check Weather", name: nil, class: "btn btn-primary" %>
  <% end %>
</div>


<div>
<% if @weather.present? %>
  <h3><%= @weather.location %></h3>
  <p>The temperature is:
    <%= @weather.temp %> °F</p>
  <p>Current conditions:
    <%= @weather.desc %></p>
  <p>Feels like:
    <%= @weather.feels_like %> °F</p>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weatherapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>